In [13]:
!pip install numpy

In [4]:
import numpy as np

## Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
print(type(array_1d))
print(array_1d.shape)

1D Array: [1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
import numpy as np

## Create a 2D array
array_2d = np.array([[1, 2, 3, 4, 5, 6]])
print("\n2D Array:\n", array_2d)



2D Array:
 [[1 2 3 4 5 6]]


In [15]:
import numpy as np
## Create a true 3D array with shape (2, 4, 3)
array_3d_true = np.ones((2, 4, 3))
print("\n3D Array (2x4x3) with all elements as 1:\n", array_3d_true)
print("Shape:", array_3d_true.shape)
print("Type:", type(array_3d_true))



3D Array (2x4x3) with all elements as 1:
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
Shape: (2, 4, 3)
Type: <class 'numpy.ndarray'>


In [16]:
### numpy vectorized operations
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition
sum_arr = arr1 + arr2   
print("Element-wise Addition:", sum_arr)    

# Element-wise multiplication
prod_arr = arr1 * arr2
print("Element-wise Multiplication:", prod_arr) 



Element-wise Addition: [11 22 33 44 55]
Element-wise Multiplication: [ 10  40  90 160 250]


In [17]:
## universal functions
import numpy as np
arr = np.array([2,3,4,5,6])
sqrt_arr = np.sqrt(arr)
print("Square Roots:", sqrt_arr)
exp_arr = np.exp(arr)
print("Exponentials:", exp_arr)
log_arr = np.log(arr)
print("Natural Logarithms:", log_arr)



Square Roots: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponentials: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Natural Logarithms: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [18]:
## array indexing and slicing
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
# Indexing 
print("Element at index 2:", arr[2])
# Slicing
print("Elements from index 1 to 3:", arr[1:4])
# Negative Indexing
print("Last element using negative indexing:", arr[-1])

Element at index 2: 30
Elements from index 1 to 3: [20 30 40]
Last element using negative indexing: 50


In [20]:
arr[0]

np.int64(10)

In [21]:
### statistical concept -- Normalization
import numpy as np
data = np.array([10, 20, 30, 40, 50])
mean = np.mean(data)
std_dev = np.std(data)
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)


Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [23]:
## wap to find the mean , median and standard deviation of an array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
var = np.var(arr)
print("Mean:", mean)
print("Median:", median)        
print("Standard Deviation:", std_dev)
print("Variance:", var)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [24]:
data =np.array([10, 20, 30, 40, 50])

data>5


array([ True,  True,  True,  True,  True])